export const mockMembers = [
  {
    id: '1',
    name: 'Tayebwa Osbert',
    role: 'Father',
    initials: 'TO',
    color: '#2D5A3D',
    isAdmin: true,
    isDeceased: false,
    status: 'active',
    email: 'osbert.tayebwa@gmail.com',
    phone: '+256 700 123 456',
    nin: 'CM90200012345A',
    bloodType: 'O+',
    dob: 'March 14, 1965',
    joinedAt: 'Jan 2024',
    lastSeen: 'Just now',
  },
  {
    id: '2',
    name: 'Kyogabirwe Enid',
    role: 'Mother',
    initials: 'KE',
    color: '#5A3D6E',
    isAdmin: false,
    isDeceased: false,
    status: 'active',
    email: 'enid.kyogabirwe@gmail.com',
    phone: '+256 701 234 567',
    nin: 'CM90200012346B',
    bloodType: 'A+',
    dob: 'July 22, 1968',
    joinedAt: 'Jan 2024',
    lastSeen: '2 hours ago',
  },
  {
    id: '3',
    name: 'Tayebwa Stuart',
    role: '1st Born',
    initials: 'TS',
    color: '#3D5A8A',
    isAdmin: false,
    isDeceased: false,
    status: 'active',
    email: 'stuart.tayebwa@gmail.com',
    phone: '+256 702 345 678',
    nin: 'CM90200012347C',
    bloodType: 'B+',
    dob: 'February 5, 1990',
    joinedAt: 'Feb 2024',
    lastSeen: 'Yesterday',
  },
  {
    id: '4',
    name: 'Turyaguma Osbert',
    role: '2nd Born',
    initials: 'TO',
    color: '#8A5A3D',
    isAdmin: false,
    isDeceased: false,
    status: 'active',
    email: 'osbert.turyaguma@gmail.com',
    phone: '+256 703 456 789',
    nin: 'CM90200012348D',
    bloodType: 'O-',
    dob: 'November 18, 1993',
    joinedAt: 'Feb 2024',
    lastSeen: '3 days ago',
  },
  {
    id: '5',
    name: 'Tumusiime Emmanuel',
    role: '3rd Born',
    initials: 'TE',
    color: '#3D7A6E',
    isAdmin: false,
    isDeceased: false,
    status: 'active',
    email: 'emmanuel.tumusiime@gmail.com',
    phone: '+256 704 567 890',
    nin: 'CM90200012349E',
    bloodType: 'AB+',
    dob: 'June 30, 1997',
    joinedAt: 'Mar 2024',
    lastSeen: '1 week ago',
  },
  {
    id: '6',
    name: 'James Nakimera',
    role: 'Grandfather',
    initials: 'JN',
    color: '#6E3D3D',
    isAdmin: false,
    isDeceased: false,
    status: 'active',
    email: 'james.nakimera@gmail.com',
    phone: '+256 705 678 901',
    nin: 'CM90200012350F',
    bloodType: 'A-',
    dob: 'August 10, 1940',
    joinedAt: 'Jan 2024',
    lastSeen: '2 weeks ago',
  },
  {
    id: '7',
    name: 'Ruth Nakimera',
    role: 'Grandmother',
    initials: 'RN',
    color: '#6E5A3D',
    isAdmin: false,
    isDeceased: true,
    status: 'active',
    email: '—',
    phone: '—',
    nin: 'CM90200012351G',
    bloodType: 'B-',
    dob: 'April 3, 1945',
    joinedAt: 'Jan 2024',
    lastSeen: '—',
  },
  {
    id: '8',
    name: 'Christine Opio',
    role: 'Aunt',
    initials: 'CO',
    color: '#3D6E5A',
    isAdmin: false,
    isDeceased: false,
    status: 'inactive',
    email: 'christine.opio@gmail.com',
    phone: '+256 706 789 012',
    nin: 'CM90200012352H',
    bloodType: 'O+',
    dob: 'December 12, 1972',
    joinedAt: 'Apr 2024',
    lastSeen: '1 month ago',
  },
];

export const mockActivityLog = [
  { id: 'l1', actor: 'Tayebwa Osbert',   action: 'reset password for',  target: 'Tumusiime Emmanuel', time: '10 mins ago',  icon: '🔑' },
  { id: 'l2', actor: 'Tayebwa Stuart',   action: 'uploaded 12 photos to', target: 'Memory Book',       time: '2 hours ago',  icon: '📸' },
  { id: 'l3', actor: 'Kyogabirwe Enid',  action: 'posted announcement:', target: '"Prayer Weekend"',   time: '5 hours ago',  icon: '📣' },
  { id: 'l4', actor: 'Christine Opio',   action: 'triggered',            target: 'SOS Alert',          time: 'Yesterday',    icon: '🆘' },
  { id: 'l5', actor: 'Tayebwa Osbert',   action: 'added new member:',    target: 'Tumusiime Emmanuel', time: '2 days ago',   icon: '👤' },
  { id: 'l6', actor: 'Turyaguma Osbert', action: 'created vault:',       target: '"Academic Docs"',    time: '3 days ago',   icon: '🗄️' },
  { id: 'l7', actor: 'Tayebwa Osbert',   action: 'approved deletion of', target: '3 memory photos',    time: '5 days ago',   icon: '🗑️' },
];

export const mockDeletionRequests = [
  {
    id: 'd1',
    requestedBy: 'Tayebwa Stuart',
    requestedByInitials: 'TS',
    requestedByColor: '#3D5A8A',
    item: 'Christmas 2023 group photo',
    reason: 'Bad quality, blurry image',
    time: '1 hour ago',
  },
  {
    id: 'd2',
    requestedBy: 'Kyogabirwe Enid',
    requestedByInitials: 'KE',
    requestedByColor: '#5A3D6E',
    item: 'Family trip video (3:42)',
    reason: 'Accidentally uploaded wrong file',
    time: '2 days ago',
  },
];

export const mockStats = {
  totalMembers: 8,
  activeMembers: 7,
  announcements: 5,
  mediaItems: 83,
  vaultDocs: 14,
  pendingDeletions: 2,
  sosAlerts: 1,
  wallPosts: 12,
};
