# Generated by Django 6.0.5 on 2026-05-23 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_tree', '0002_alter_family_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('file', models.FileField(upload_to='memory_items/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='memory_thumbnails/%Y/%m/')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='family_tree.family')),
                ('tagged_members', models.ManyToManyField(blank=True, related_name='tagged_in_memories', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory Item',
                'verbose_name_plural': 'Memory Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletions', to=settings.AUTH_USER_MODEL)),
                ('memory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='memory_book.memoryitem')),
            ],
        ),
    ]
