export const mockEvents = [
  {
    id: 'e1',
    title: "Grace's Birthday",
    date: '2026-06-03',
    type: 'birthday',
    color: '#8A5A3D',
    createdBy: 'Robert Nakimera',
    createdByInitials: 'RN',
    createdByColor: '#2D5A3D',
    recurrence: 'yearly',
    description: 'Mom turns 57 this year. Planning a surprise dinner.',
    time: null,
  },
  {
    id: 'e2',
    title: 'Family Reunion',
    date: '2026-06-12',
    type: 'event',
    color: '#2D5A3D',
    createdBy: 'Robert Nakimera',
    createdByInitials: 'RN',
    createdByColor: '#2D5A3D',
    recurrence: 'none',
    description: 'Annual family gathering at the Kampala home. Everyone must attend.',
    time: '10:00 AM',
  },
  {
    id: 'e3',
    title: 'School Closing Day',
    date: '2026-06-14',
    type: 'event',
    color: '#3D5A8A',
    createdBy: 'Grace Nakimera',
    createdByInitials: 'GN',
    createdByColor: '#5A3D6E',
    recurrence: 'none',
    description: 'End of Term 2. Pick up Paul by 2pm.',
    time: '2:00 PM',
  },
  {
    id: 'e4',
    title: "David's Anniversary",
    date: '2026-06-22',
    type: 'birthday',
    color: '#5A3D6E',
    createdBy: 'Grace Nakimera',
    createdByInitials: 'GN',
    createdByColor: '#5A3D6E',
    recurrence: 'yearly',
    description: "David and Christine's 2nd wedding anniversary.",
    time: null,
  },
  {
    id: 'e5',
    title: 'Sunday Family Prayers',
    date: '2026-06-07',
    type: 'event',
    color: '#C9A84C',
    createdBy: 'Grace Nakimera',
    createdByInitials: 'GN',
    createdByColor: '#5A3D6E',
    recurrence: 'weekly',
    description: 'Weekly family prayer session at home.',
    time: '8:00 AM',
  },
  {
    id: 'e6',
    title: 'Sunday Family Prayers',
    date: '2026-06-14',
    type: 'event',
    color: '#C9A84C',
    createdBy: 'Grace Nakimera',
    createdByInitials: 'GN',
    createdByColor: '#5A3D6E',
    recurrence: 'weekly',
    description: 'Weekly family prayer session at home.',
    time: '8:00 AM',
  },
  {
    id: 'e7',
    title: 'Sunday Family Prayers',
    date: '2026-06-21',
    type: 'event',
    color: '#C9A84C',
    createdBy: 'Grace Nakimera',
    createdByInitials: 'GN',
    createdByColor: '#5A3D6E',
    recurrence: 'weekly',
    description: 'Weekly family prayer session at home.',
    time: '8:00 AM',
  },
  {
    id: 'e8',
    title: 'Sunday Family Prayers',
    date: '2026-06-28',
    type: 'event',
    color: '#C9A84C',
    createdBy: 'Grace Nakimera',
    createdByInitials: 'GN',
    createdByColor: '#5A3D6E',
    recurrence: 'weekly',
    description: 'Weekly family prayer session at home.',
    time: '8:00 AM',
  },
  {
    id: 'e9',
    title: "James's Birthday",
    date: '2026-06-29',
    type: 'birthday',
    color: '#6E3D3D',
    createdBy: 'Robert Nakimera',
    createdByInitials: 'RN',
    createdByColor: '#2D5A3D',
    recurrence: 'yearly',
    description: "Grandfather James turns 78.",
    time: null,
  },
  {
    id: 'e10',
    title: 'Hospital Checkup',
    date: '2026-06-17',
    type: 'event',
    color: '#C0392B',
    createdBy: 'Grace Nakimera',
    createdByInitials: 'GN',
    createdByColor: '#5A3D6E',
    recurrence: 'none',
    description: "Dad's monthly cardiology checkup at Mulago Hospital.",
    time: '9:30 AM',
  },
  {
    id: 'e11',
    title: 'Rent Due',
    date: '2026-06-30',
    type: 'event',
    color: '#3D7A6E',
    createdBy: 'Robert Nakimera',
    createdByInitials: 'RN',
    createdByColor: '#2D5A3D',
    recurrence: 'monthly',
    description: 'Monthly rent payment for the Entebbe property.',
    time: null,
  },
  {
    id: 'e12',
    title: "Sarah's Graduation",
    date: '2026-07-10',
    type: 'event',
    color: '#3D5A8A',
    createdBy: 'Sarah Nakimera',
    createdByInitials: 'SN',
    createdByColor: '#8A5A3D',
    recurrence: 'none',
    description: "Sarah's university graduation ceremony at Makerere.",
    time: '10:00 AM',
  },
];

export const RECURRENCE_LABELS = {
  none:    null,
  daily:   '🔁 Daily',
  weekly:  '🔁 Weekly',
  monthly: '🔁 Monthly',
  yearly:  '🔁 Yearly',
};

export const EVENT_TYPE_COLORS = {
  birthday: { bg: 'rgba(201,168,76,0.10)',  border: 'rgba(201,168,76,0.3)',  text: '#A07C20' },
  event:    { bg: 'rgba(45,90,61,0.08)',    border: 'rgba(45,90,61,0.2)',    text: '#2D5A3D' },
};