# Generated by Django 6.0.5 on 2026-05-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
