# Generated by Django 6.0.5 on 2026-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_familymember_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family_role',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('grandfather', 'Grandfather'), ('grandmother', 'GrandMother')], db_index=True, help_text='e.g. Father, Mother, 1st Born, etc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
