# Generated by Django 6.0.5 on 2026-06-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_familymember_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Linked Firebase Auth UID, set on first Flutter login', max_length=128, null=True, unique=True),
        ),
    ]
