# Generated by Django 6.0.5 on 2026-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
