export const mockFamilyLocations = [
  {
    id: 'l1',
    name: 'Tayebwa OSbert',
    initials: 'TO',
    color: '#2D5A3D',
    role: 'Father',
    location: 'Kampala, Uganda',
    address: 'Buwaama, Kampala',
    lat: 0.3136,
    lng: 32.5811,
    sharedAt: '10 mins ago',
    isOnline: true,
  },
  {
    id: 'l2',
    name: 'Kyogabirwe Enid',
    initials: 'KE',
    color: '#5A3D6E',
    role: 'Mother',
    location: 'Ntungamo, Uganda',
    address: 'Ntungamo Road',
    lat: 0.0512,
    lng: 32.4637,
    sharedAt: '32 mins ago',
    isOnline: true,
  },
  {
    id: 'l3',
    name: 'Tayebwa Stuart',
    initials: 'TS',
    color: '#3D5A8A',
    role: '1st Born',
    location: 'Kampala, Uganda',
    address: 'Makerere University',
    lat: 0.3349,
    lng: 32.5677,
    sharedAt: '1 hr ago',
    isOnline: false,
  },
  {
    id: 'l4',
    name: 'Turyaguma Osbert',
    initials: 'TO',
    color: '#8A5A3D',
    role: '2nd Born',
    location: 'Kampala, Uganda',
    address: 'Mengo SS',
    lat: 2.7748,
    lng: 32.2990,
    sharedAt: '3 hrs ago',
    isOnline: false,
  },
];

export const mockSOSHistory = [
  {
    id: 's1',
    triggeredBy: 'Tumusiime Emmanuel',
    triggeredByInitials: 'TE',
    triggeredByColor: '#8A5A3D',
    message: 'Car broke down on the highway, need help.',
    location: 'Gulu Highway, km 45',
    triggeredAt: 'Yesterday, 6:42 PM',
    status: 'resolved',
    safeResponses: [
      { name: 'Robert', initials: 'RN', color: '#2D5A3D' },
      { name: 'Grace',  initials: 'GN', color: '#5A3D6E' },
      { name: 'David',  initials: 'DN', color: '#3D5A8A' },
    ],
  },
  {
    id: 's2',
    triggeredBy: 'Nahabwe Engreed',
    triggeredByInitials: 'NE',
    triggeredByColor: '#3D7A6E',
    message: null,
    location: 'Kampala Central',
    triggeredAt: '3 days ago, 11:15 AM',
    status: 'resolved',
    safeResponses: [
      { name: 'Robert', initials: 'RN', color: '#2D5A3D' },
      { name: 'Grace',  initials: 'GN', color: '#5A3D6E' },
    ],
  },
];

export const mockActiveSOSTemplate = {
  id: 'active1',
  triggeredBy: 'You',
  triggeredByInitials: 'RN',
  triggeredByColor: '#2D5A3D',
  location: 'Detecting your location...',
  triggeredAt: 'Just now',
  safeResponses: [],
};