// ─── Watchlist Mock Data ──────────────────────────────────────────────────────

export const mockWatchlistItems = [
  {
    id: 'w1',
    title: 'The Lion of Lango',
    type: 'movie',
    genre: 'Drama',
    year: 2023,
    duration: '2h 14m',
    emoji: '🦁',
    color: '#3D5A8A',
    status: 'pending',
    rating: 4,
    addedBy: 'Tayebwa Osbert',
    addedByInitials: 'TO',
    addedByColor: '#2D5A3D',
    sharedWith: [
      { initials: 'TO', color: '#2D5A3D' },
      { initials: 'KE', color: '#5A3D6E' },
      { initials: 'TS', color: '#3D5A8A' },
    ],
    note: 'Said to be an incredible story based on real events.',
    addedDate: '2 days ago',
  },
  {
    id: 'w2',
    title: 'Interstellar',
    type: 'movie',
    genre: 'Sci-Fi',
    year: 2014,
    duration: '2h 49m',
    emoji: '🌌',
    color: '#8A5A3D',
    status: 'pending',
    rating: 5,
    addedBy: 'Tayebwa Stuart',
    addedByInitials: 'TS',
    addedByColor: '#3D5A8A',
    sharedWith: [
      { initials: 'TS', color: '#3D5A8A' },
    ],
    note: '',
    addedDate: '4 days ago',
  },
  {
    id: 'w3',
    title: 'The Blacklist',
    type: 'series',
    genre: 'Crime',
    year: 2013,
    duration: 'Season 1–4',
    emoji: '🕵️',
    color: '#2D5A3D',
    status: 'pending',
    rating: 4,
    addedBy: 'Turyaguma Osbert',
    addedByInitials: 'TO2',
    addedByColor: '#8A5A3D',
    sharedWith: [
      { initials: 'TO2', color: '#8A5A3D' },
      { initials: 'TE',  color: '#3D7A6E' },
    ],
    note: 'Start from Season 1, do not skip.',
    addedDate: '1 week ago',
  },
  {
    id: 'w4',
    title: 'The Crown',
    type: 'series',
    genre: 'Historical',
    year: 2016,
    duration: 'Season 1–6',
    emoji: '👑',
    color: '#5A3D6E',
    status: 'pending',
    rating: 5,
    addedBy: 'Kyogabirwe Enid',
    addedByInitials: 'KE',
    addedByColor: '#5A3D6E',
    sharedWith: [
      { initials: 'KE', color: '#5A3D6E' },
    ],
    note: '',
    addedDate: '1 week ago',
  },
  {
    id: 'w5',
    title: 'Our Planet II',
    type: 'series',
    genre: 'Documentary',
    year: 2023,
    duration: '4 Episodes',
    emoji: '🌿',
    color: '#3D7A6E',
    status: 'pending',
    rating: 5,
    addedBy: 'Tumusiime Emmanuel',
    addedByInitials: 'TE',
    addedByColor: '#3D7A6E',
    sharedWith: [
      { initials: 'TE', color: '#3D7A6E' },
    ],
    note: '',
    addedDate: '2 weeks ago',
  },
  {
    id: 'w6',
    title: 'Black Panther',
    type: 'movie',
    genre: 'Action',
    year: 2018,
    duration: '2h 14m',
    emoji: '🦅',
    color: '#2D5A3D',
    status: 'watched',
    rating: 5,
    addedBy: 'Tayebwa Osbert',
    addedByInitials: 'TO',
    addedByColor: '#2D5A3D',
    sharedWith: [
      { initials: 'TO',  color: '#2D5A3D' },
      { initials: 'KE',  color: '#5A3D6E' },
      { initials: 'TS',  color: '#3D5A8A' },
      { initials: 'TO2', color: '#8A5A3D' },
    ],
    note: "Dad's favourite. Great movie overall — 5 stars from everyone.",
    addedDate: '1 month ago',
    watchedDate: '3 weeks ago',
  },
  {
    id: 'w7',
    title: 'Gravity',
    type: 'movie',
    genre: 'Sci-Fi',
    year: 2013,
    duration: '1h 31m',
    emoji: '🚀',
    color: '#3D5A8A',
    status: 'watched',
    rating: 4,
    addedBy: 'Tayebwa Osbert',
    addedByInitials: 'TO',
    addedByColor: '#2D5A3D',
    sharedWith: [
      { initials: 'TO', color: '#2D5A3D' },
      { initials: 'KE', color: '#5A3D6E' },
    ],
    note: '',
    addedDate: '1 month ago',
    watchedDate: '3 weeks ago',
  },
  {
    id: 'w8',
    title: 'Coming to America',
    type: 'movie',
    genre: 'Comedy',
    year: 1988,
    duration: '1h 57m',
    emoji: '😂',
    color: '#C9A84C',
    status: 'watched',
    rating: 4,
    addedBy: 'Kyogabirwe Enid',
    addedByInitials: 'KE',
    addedByColor: '#5A3D6E',
    sharedWith: [
      { initials: 'TO', color: '#2D5A3D' },
      { initials: 'KE', color: '#5A3D6E' },
      { initials: 'TS', color: '#3D5A8A' },
    ],
    note: 'Classic! Mum insisted.',
    addedDate: '2 months ago',
    watchedDate: '6 weeks ago',
  },
];

// ─── Genre summary (derived, but kept as mock for convenience) ────────────────
export const mockGenreSummary = [
  { id: 'g1', genre: 'Action',      emoji: '🎬', count: 2, color: '#3D5A8A', bg: 'rgba(61,90,138,.07)',  border: 'rgba(61,90,138,.18)' },
  { id: 'g2', genre: 'Drama',       emoji: '📖', count: 3, color: '#2D5A3D', bg: 'rgba(45,90,61,.07)',   border: 'rgba(45,90,61,.18)'  },
  { id: 'g3', genre: 'Sci-Fi',      emoji: '🚀', count: 3, color: '#5A3D8A', bg: 'rgba(90,61,138,.07)',  border: 'rgba(90,61,138,.18)' },
  { id: 'g4', genre: 'Documentary', emoji: '🌿', count: 2, color: '#2D7A50', bg: 'rgba(45,122,80,.07)',  border: 'rgba(45,122,80,.18)' },
  { id: 'g5', genre: 'Historical',  emoji: '🏛️', count: 1, color: '#8A5A3D', bg: 'rgba(138,90,61,.07)', border: 'rgba(138,90,61,.18)' },
  { id: 'g6', genre: 'Crime',       emoji: '🕵️', count: 1, color: '#6E3D3D', bg: 'rgba(110,61,61,.07)', border: 'rgba(110,61,61,.18)' },
];

// ─── Per-member contribution ──────────────────────────────────────────────────
export const mockMemberContributions = [
  { id: 'm1', name: 'Tayebwa Osbert',     initials: 'TO',  color: '#2D5A3D', count: 4 },
  { id: 'm2', name: 'Kyogabirwe Enid',    initials: 'KE',  color: '#5A3D6E', count: 3 },
  { id: 'm3', name: 'Tayebwa Stuart',     initials: 'TS',  color: '#3D5A8A', count: 3 },
  { id: 'm4', name: 'Tumusiime Emmanuel', initials: 'TE',  color: '#3D7A6E', count: 2 },
];