// ─── Announcements Mock Data ──────────────────────────────────────────────────

export const mockAnnouncements = [
  {
    id: 'a1',
    author: 'Tayebwa Osbert',
    authorInitials: 'TO',
    authorColor: '#2D5A3D',
    title: 'Family Reunion — July 12th',
    body: 'We are planning a family gathering at the home in Kampala. Please confirm your attendance by end of this week so we can plan catering and seating accordingly. Children are welcome — there will be activities for them.',
    isUrgent: false,
    audience: 'All Members',
    time: '2 hours ago',
    replies: [
      { id: 'r1', author: 'Kyogabirwe Enid',    authorInitials: 'KE', authorColor: '#5A3D6E', text: 'We will be there! Looking forward to seeing everyone.',          time: '1 hour ago'  },
      { id: 'r2', author: 'Tayebwa Stuart',      authorInitials: 'TS', authorColor: '#3D5A8A', text: 'Confirmed. I will arrive Friday evening.',                       time: '45 mins ago' },
      { id: 'r3', author: 'Christine Opio',      authorInitials: 'CO', authorColor: '#3D6E5A', text: 'I will be traveling from Gulu — should be there by noon.',       time: '30 mins ago' },
    ],
    poll: null,
    hasVoiceNote: false,
  },
  {
    id: 'a2',
    author: 'Tayebwa Osbert',
    authorInitials: 'TO',
    authorColor: '#2D5A3D',
    title: 'Important: Update your emergency contacts',
    body: 'Please make sure your profiles have current phone numbers and medical details updated before next week. This is critical for the family directory. Admin will review and confirm all updates by Sunday.',
    isUrgent: true,
    audience: 'All Members',
    time: 'Yesterday',
    replies: [
      { id: 'r4', author: 'Tumusiime Emmanuel', authorInitials: 'TE', authorColor: '#3D7A6E', text: 'Done! Updated my blood type and new contact.', time: '20 hours ago' },
    ],
    poll: null,
    hasVoiceNote: true,
  },
  {
    id: 'a3',
    author: 'Tayebwa Stuart',
    authorInitials: 'TS',
    authorColor: '#3D5A8A',
    title: 'New photos added to memory book',
    body: "Added pictures from last month's graduation ceremony. Check the Memory Book under Events. There are over 40 photos — I've organised them by year and event. Feel free to tag yourselves!",
    isUrgent: false,
    audience: 'All Members',
    time: '3 days ago',
    replies: [
      { id: 'r5', author: 'Kyogabirwe Enid',   authorInitials: 'KE', authorColor: '#5A3D6E', text: 'Beautiful photos! Thank you for capturing those moments.',        time: '2 days ago'  },
      { id: 'r6', author: 'Christine Opio',     authorInitials: 'CO', authorColor: '#3D6E5A', text: "I've tagged myself in the group photo. Great memories!",          time: '2 days ago'  },
      { id: 'r7', author: 'Turyaguma Osbert',   authorInitials: 'TO', authorColor: '#8A5A3D', text: 'Can you add the ones from the dinner too?',                       time: '1 day ago'   },
      { id: 'r8', author: 'Tayebwa Stuart',     authorInitials: 'TS', authorColor: '#3D5A8A', text: 'Yes, will upload them this evening.',                             time: '22 hours ago'},
    ],
    poll: {
      question: 'Which album should we print for the family archive?',
      options: [
        { id: 'p1', label: 'Graduation Ceremony', votes: 5 },
        { id: 'p2', label: 'Christmas 2024',       votes: 3 },
        { id: 'p3', label: 'Family Trip Album',    votes: 2 },
      ],
      deadline: 'Jun 10',
      totalVotes: 10,
      userVoted: null,
    },
    hasVoiceNote: false,
  },
  {
    id: 'a4',
    author: 'Kyogabirwe Enid',
    authorInitials: 'KE',
    authorColor: '#5A3D6E',
    title: 'Weekend prayer and fasting — June 7–8',
    body: "Calling all family members to join in a weekend of prayer and fasting as we seek God's guidance for the family this season. We will share prayer points on the Prayer Wall. Please participate from wherever you are.",
    isUrgent: false,
    audience: 'All Members',
    time: '5 days ago',
    replies: [],
    poll: {
      question: 'Will you be joining the fasting weekend?',
      options: [
        { id: 'p4', label: 'Yes, both days',            votes: 6 },
        { id: 'p5', label: 'Saturday only',             votes: 2 },
        { id: 'p6', label: 'Sunday only',               votes: 1 },
        { id: 'p7', label: 'Praying along, not fasting',votes: 1 },
      ],
      deadline: 'Jun 6',
      totalVotes: 10,
      userVoted: 'p4',
    },
    hasVoiceNote: false,
  },
  {
    id: 'a5',
    author: 'Christine Opio',
    authorInitials: 'CO',
    authorColor: '#3D6E5A',
    title: 'Safe travels update — back in Gulu',
    body: 'Just wanted to let everyone know I arrived safely in Gulu. The road was good. I will be back for the reunion in July. Thank you all for the prayers.',
    isUrgent: false,
    audience: 'All Members',
    time: '1 week ago',
    replies: [
      { id: 'r9', author: 'Tayebwa Osbert', authorInitials: 'TO', authorColor: '#2D5A3D', text: 'Glad you arrived safely, Christine. We will see you in July.', time: '1 week ago' },
    ],
    poll: null,
    hasVoiceNote: false,
  },
];